### ISSUE TITLE
Autocalibration?

### ISSUE THREAD

**Issue by karabas** [tkurbad/Marlin#1]
Did you implement any autocalibration command like G30 in richcatt Marlin?

**Comment by tkurbad** [comment]
What brand/model of printer do you use?
This branch uses the autoleveling features that are part of Marlin now, i.e.

G29 (**see Wiki of original Marlin for explanations**): Do a complete auto bed leveling with the probe chosen in Configuration.h
G30 probe single points on the Z-Axis.

I added FSR code for G29 specific to the Deltaprintr (www.deltaprintr.com). If you use another printer/mainboard, this most probably won't work.

**Comment by tkurbad** [comment]
Please reopen, if you have further questions.
